#!/bin/bash

function tmux_web {
  SESSION_NAME=$1
  FILE_NAME=$2
  
  # create a new session. Note the -d flag, we do not want to attach just yet!
  tmux new-session -s $SESSION_NAME -n 'th' -d
  
  tmux send-keys -t $SESSION_NAME:th.0 "vim $FILE_NAME" C-j
  
  # split the window *vertically*
  tmux split-window -v -p 20
  
  # finally attach to the session
  tmux attach -t $SESSION_NAME
}


#new session base name is current directory name
DIR_NAME=${PWD##*/}

echo "Trying to create new Tmux session with name '$DIR_NAME'."
tmux has-session -t $DIR_NAME 2>/dev/null
if [ $? -eq 1 ]
then
  echo "Session not found. Create Session '$DIR_NAME'."
  tmux_web $DIR_NAME $1
else
  #random string as new session suffix
  RAND_NUMB=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 2 | head -n 1)
  echo "Session found. Create session with name '$DIR_NAME$RAND_NUMB'"
  tmux_web "$DIR_NAME$RAND_NUMB" $1
fi

echo "Start tmux session $DIR_NAME."
